// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appPerfinAPI.Data;

namespace appPerfinAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("appPerfinAPI.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Alimentação",
                            Sigla = "ALI"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Bar / Festas",
                            Sigla = "BAR"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Refeição",
                            Sigla = "REF"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Lazer / Esporte",
                            Sigla = "LAZ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
